# Generated by Django 5.0.6 on 2024-07-02 20:43

import core_apps.visitor_access.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        default=core_apps.visitor_access.models.generate_access_code,
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("visitor_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("", "Select gender"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_registration",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("additional_information", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("accepted_date", models.DateTimeField(blank=True, null=True)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visitor Access Request",
            },
        ),
    ]
